pipeline {
    agent any
    stages {
        stage('Fetch Index File') {
            steps {
                // Create directory
                sh 'mkdir -p site'
                
                // Use git to get the file instead of curl
                sh '''
                    git clone https://github.com/Abo1406/devops-static-site.git temp
                    if [ -f temp/site/index.html ]; then
                        cp temp/site/index.html site/
                    elif [ -f temp/index.html ]; then
                        cp temp/index.html site/
                    else
                        echo "index.html not found in repository"
                        ls -la temp/
                        exit 1
                    fi
                    rm -rf temp
                '''
            }
        }
        stage('Deploy to HTTPD') {
            steps {
                sshPublisher(
                    publishers: [
                        sshPublisherDesc(
                            configName: 'ozgecmis.online',
                            transfers: [
                                sshTransfer(
                                    sourceFiles: 'site/index.html',
                                    removePrefix: 'site',
                                    remoteDirectory: '/var/www/html',
                                    execCommand: '''
                                        sudo chmod 644 /var/www/html/index.html
                                        sudo systemctl restart httpd
                                    '''
                                )
                            ],
                            usePromotionTimestamp: false,
                            useWorkspaceInPromotion: false,
                            verbose: true
                        )
                    ]
                )
            }
        }
    }
    post {
        success {
            echo "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
        }
        failure {
            echo "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
        }
    }
}
