---
- name: Install Jenkins on RedHat/CentOS using native modules
  hosts: webserver
  become: true

  tasks:
    - name: Add Jenkins YUM repo
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0644'

    - name: Import Jenkins GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Upgrade all packages to latest
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Install required dependencies
      ansible.builtin.yum:
        name:
          - fontconfig
          - java-21-openjdk
        state: present

    - name: Install Jenkins package
      ansible.builtin.yum:
        name: jenkins
        state: present

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Ensure Jenkins is enabled and running
      ansible.builtin.service:
        name: jenkins
        enabled: yes
        state: started

    - name: Read Jenkins initial admin password
      ansible.builtin.slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_passwd_raw

    - name: Show Jenkins initial admin password
      ansible.builtin.debug:
        msg: "{{ (jenkins_passwd_raw.content | b64decode).strip() }}"
